version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: car_shop_db
    environment:
      POSTGRES_DB: car_shop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  order-postgres:
    image: postgres:16
    container_name: order_db
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - order_postgres_data:/var/lib/postgresql/data

  storage-postgres:
    image: postgres:16
    container_name: storage_db
    environment:
      POSTGRES_DB: storage_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - storage_postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: car_shop_keycloak
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"
    volumes:
      - ./docker/keycloak:/opt/keycloak/data/import
      - keycloak_data:/opt/keycloak/data

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: car_shop_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: grisha
      RABBITMQ_DEFAULT_PASS: grisha

volumes:
  postgres_data:
  order_postgres_data:
  storage_postgres_data:
  keycloak_data: